mapped_gene_names = {
    "UBE2I": "UBE2I",
    "SUMO1": "SUMO1",
    "CALM1": "CALM1",
    "TPK1": "TPK1",
    "hYAP65 WW domain": "YAP1",
    "BRCA1 RING domain": "BRCA1",
    "CBS": "CBS",
    "PTEN": "PTEN",
    "TPMT": "TPMT",
    "HMGCR": "HMGCR",
    "LDLRAP1": "LDLRAP1",
    "Src catalytic domain": "SRC",
    "Src SH4 domain": "SRC",
    "S505N MPL": "MPL",
    "MPL": "MPL",
    "alpha-synuclein": "SNCA",
    "CD86": "CD86",
    "CCR5": "CCR5",
    "CXCR4": "CXCR4",
    "MTHFR": "MTHFR",
    "MSH2": "MSH2",
    "Glycophorin A": "GYPA",
    "human L-Selectin": "SELL",
    "ErbB2": "ERBB2",
    "PSD95 PDZ3": "DLG4",
    "NUDT15": "NUDT15",
    "Ras": "HRAS",
    "Aβ42": "APP",
    "p53": "TP53",
    "TARDBP": "TARDBP",
    "RAF": "RAF1",
    "CYP2C9": "CYP2C9",
    "CYP2C19": "CYP2C19",
    "NCS1": "NCS1",
    "GDI1": "GDI1",
    "TECR": "TECR",
    "TP53 (P72R)": "TP53",
    "ACE2": "ACE2",
    "IGHG1": "IGHG1",
    "VKOR": "VKORC1",
    "BRCA1": "BRCA1",
    "BRAF": "BRAF",
    "BRCA1 translation start through RING domain": "BRCA1",
    "KCNQ1": "KCNQ1",
    "KCNQ4": "KCNQ4",
    "GCK": "GCK",
    "BRCA1 Exon 16": "BRCA1",
    "BRCA1 Exon 15": "BRCA1",
    "BRCA1 Exon 22": "BRCA1",
    "BRCA1 Exon 23": "BRCA1",
    "BRCA1 Exon 2": "BRCA1",
    "BRCA1 Exon 3": "BRCA1",
    "BRCA1 Exon 17": "BRCA1",
    "BRCA1 Locus": "BRCA1",
    "BRCA1 Exon 4": "BRCA1",
    "BRCA1 Exon 5": "BRCA1",
    "BRCA1 Exon 20": "BRCA1",
    "BRCA1 Exon 18": "BRCA1",
    "BRCA1 Exon 19": "BRCA1",
    "BRCA1 Exon 21": "BRCA1",
    "SCN5A": "SCN5A",
    "RHO": "RHO",
    "MAPK1": "MAPK1",
    "PARP1": "PARP1",
    "GB1": "GABBR1",
    "AID": "AICDA",
    "HMBS": "HMBS",
    "JAK1": "JAK1",
    "APP": "APP",
    "PRKN": "PRKN",
    "KRAS": "KRAS",
    "FYN SH3 domain": "FYN",
    "FYN SH3 domain (E24S)": "FYN",
    "FYN SH3 domain (F20A)": "FYN",
    "FYN SH3 domain (L7S)": "FYN",
    "FYN SH3 domain (V55A)": "FYN",
    "EPHB2 SAM domain": "EPHB2",
    "LCK": "LCK",
    "UBR5": "UBR5",
    "PIN1 WW domain": "PIN1",
    "RAD23A UBA domain": "RAD23A",
    "SMN Tudor domain": "SMN1",
    "CPA2 activation domain": "CPA2",
    "BTK": "BTK",
    "NPHP1": "NPHP1",
    "NPHP1 (F13S)": "NPHP1",
    "NPHP1 (V29A)": "NPHP1",
    "UBC": "UBC",
    "UBC (F13S)": "UBC",
    "UBC (L3A)": "UBC",
    "UBC (I3A)": "UBC",
    "UBC (L15S)": "UBC",
    "UBC (L43A)": "UBC",
    "UBC (L67S)": "UBC",
    "UBC (pross10)": "UBC",
    "UBC (pross7)": "UBC",
    "PKN1": "PKN1",
    "PRPF40A": "PRPF40A",
    "OBSCN": "OBSCN",
    "OSTF1": "OSTF1",
    "HNRNPUL1": "HNRNPUL1",
    "HUWE1": "HUWE1",
    "CD2AP (pross9)": "CD2AP",
    "SQSTM1": "SQSTM1",
    "CBX7 chromo domain": "CBX7",
    "CBX4 chromo domain": "CBX4",
    "PIN1": "PIN1",
    "FKBP3": "FKBP3",
    "PTK6 SH3 domain": "PTK6",
    "RALBP1": "RALBP1",
    "PITX2 homeodomain": "PITX2",
    "PITX2 homeodomain (R24H mutant)": "PITX2",
    "NKX3-1": "NKX3-1",
    "DNAJB2": "DNAJB2",
    "DNAJA1": "DNAJA1",
    "AMFR": "AMFR",
    "ALX4": "ALX4",
    "RASA1": "RASA1",
    "PIN1 (S16E mutant)": "PIN1",
    "TCERG1 (Y438R mutant)": "TCERG1",
    "TCERG1 (Y446L mutant)": "TCERG1",
    "TCERG1 (W457F mutant)": "TCERG1",
    "TCERG1 (L453D mutant)": "TCERG1",
    "TCERG1 (L453E mutant)": "TCERG1",
    "TCERG1 (L453W mutant)": "TCERG1",
    "ATP7B": "ATP7B",
    "SORBS1": "SORBS1",
    "WWP1": "WWP1",
    "APBB3": "APBB3",
    "ITCH": "ITCH",
    "GAS7": "GAS7",
    "HECTD1": "HECTD1",
    "LASP1": "LASP1",
    "UBE4B": "UBE4B",
    "HCK": "HCK",
    "NEDD4": "NEDD4",
    "SPTAN1": "SPTAN1",
    "SPTAN1 (A10S)": "SPTAN1",
    "SPTAN1 (M24A)": "SPTAN1",
    "TNKS2": "TNKS2",
    "DUX4": "DUX4",
    "UBB": "UBB",
    "H1-0": "H1-0",
    "DNAJA3": "DNAJA3",
    "LYN": "LYN",
    "SOX30": "SOX30",
    "UBTF": "UBTF",
    "PHF20": "PHF20",
    "ABLIM2 (R14S;R16S)": "ABLIM2",
    "ASPA": "ASPA",
    "DDX3X Exon 5": "DDX3X",
    "DDX3X Exon 1": "DDX3X",
    "DDX3X Exon 2": "DDX3X",
    "DDX3X Exon 3": "DDX3X",
    "DDX3X Exon 8": "DDX3X",
    "DDX3X Exon 7": "DDX3X",
    "DDX3X Exon 14": "DDX3X",
    "DDX3X Exon 13": "DDX3X",
    "DDX3X Exon 10": "DDX3X",
    "DDX3X Exon 12": "DDX3X",
    "DDX3X Exon 16": "DDX3X",
    "DDX3X Exon 4": "DDX3X",
    "DDX3X Exon 15": "DDX3X",
    "DDX3X Exon 17": "DDX3X",
    "DDX3X Exon 6": "DDX3X",
    "DDX3X Exon 9": "DDX3X",
    "DDX3X Exon 11": "DDX3X",
    "SGCB": "SGCB",
    "COMT_ROI1_2": "COMT",
    "NDUFAF6": "NDUFAF6",
    "KCNQ2": "KCNQ2",
    "kcnq2": "KCNQ2",
    "KCNE1": "KCNE1",
    "ABL1 SH3 domain": "ABL1",
    "ABLIM3 Zinc finger, LIM-type domain": "ABLIM3",
    "ADARB1 Double-stranded RNA-binding domain": "ADARB1",
    "ADAR Z-alpha domain": "ADAR",
    "ADNP Homeobox domain": "ADNP",
    "AHI1 SH3 domain": "AHI1",
    "ALX1 Homeobox domain": "ALX1",
    "ALX3 Homeobox domain": "ALX3",
    "ALX4 Homeobox domain": "ALX4",
    "ANK1 Death domain": "ANK1",
    "ANK2 Death domain": "ANK2",
    "ANK3 Death domain": "ANK3",
    "ANKS1B Sterile alpha motif domain": "ANKS1B",
    "ANKS6 Sterile alpha motif domain": "ANKS6",
    "ARAF Raf-like Ras-binding domain": "ARAF",
    "ARHGEF28 Protein kinase C-like, phorbol ester/diacylglycerol-binding domain": "ARHGEF28",
    "ARID2 DNA-binding RFX-type winged-helix domain": "ARID2",
    "ARK2C Zinc finger, RING-type domain": "ARK2C",
    "ARX Homeobox domain": "ARX",
    "AR Zinc finger, nuclear hormone receptor-type domain": "AR",
    "ASB14 SOCS box domain": "ASB14",
    "ASPM IQ motif, EF-hand binding site domain": "ASPM",
    "ASZ1 Sterile alpha motif domain": "ASZ1",
    "ATXN7 SCA7 domain": "ATXN7",
    "AVIL Villin headpiece domain": "AVIL",
    "BAG3 WW domain": "BAG3",
    "BAG5 BAG domain": "BAG5",
    "BAZ2B Zinc finger, PHD-finger domain": "BAZ2B",
    "BLK SH3 domain": "BLK",
    "BPTF Zinc finger, PHD-finger domain": "BPTF",
    "BRAF Raf-like Ras-binding domain": "BRAF",
    "BRD4 NET domain": "BRD4",
    "BTK SH3 domain": "BTK",
    "CABP2 EF-hand domain": "CABP2",
    "CALML4 EF-hand domain": "CALML4",
    "CAPN15 Zinc finger, RanBP2-type domain": "CAPN15",
    "CASK PDZ domain": "CASK",
    "CBL Ubiquitin-associated domain": "CBL",
    "CBX5 Chromo domain": "CBX5",
    "CCAR1 SAP domain": "CCAR1",
    "CCNF F-box domain": "CCNF",
    "CD2AP SH3 domain": "CD2AP",
    "CHD3 Zinc finger, PHD-finger domain": "CHD3",
    "CHD4 Chromo domain": "CHD4",
    "CHD4 Zinc finger, PHD-finger domain": "CHD4",
    "CHD5 CHD, N-terminal domain": "CHD5",
    "CHD5 Zinc finger, PHD-finger domain": "CHD5",
    "CHD7 BRK domain": "CHD7",
    "CIDEB CIDE-N domain": "CIDEB",
    "CKS1B Cyclin-dependent kinase regulatory subunit": "CKS1B",
    "CNKSR2 Sterile alpha motif domain": "CNKSR2",
    "CPEB2 Cytoplasmic polyadenylation element-binding protein, ZZ domain": "CPEB2",
    "CRX Homeobox domain": "CRX",
    "CRYBA1 Beta/gamma crystallin domain": "CRYBA1",
    "CRYBA4 Beta/gamma crystallin domain": "CRYBA4",
    "CRYBB1 Beta/gamma crystallin domain": "CRYBB1",
    "CRYBB2 Beta/gamma crystallin domain": "CRYBB2",
    "CRYBG2 Beta/gamma crystallin domain": "CRYBG2",
    "CRYGA Beta/gamma crystallin domain": "CRYGA",
    "CRYGB Beta/gamma crystallin domain": "CRYGB",
    "CRYGC Beta/gamma crystallin domain": "CRYGC",
    "CRYGD Beta/gamma crystallin domain": "CRYGD",
    "CRYGS Beta/gamma crystallin domain": "CRYGS",
    "CSDE1 Cold-shock protein, DNA-binding domain": "CSDE1",
    "CUL9 CPH domain": "CUL9",
    "CUL9 IBR domain": "CUL9",
    "CUX1 CUT domain": "CUX1",
    "CUX1 Homeobox domain": "CUX1",
    "CUX2 CUT domain": "CUX2",
    "DBT Peripheral subunit-binding domain": "DBT",
    "DDHD2 Sterile alpha motif domain": "DDHD2",
    "DIDO1 Zinc finger, PHD-finger domain": "DIDO1",
    "DLG3 PDZ domain": "DLG3",
    "DLG4 PDZ domain": "DLG4",
    "DMBX1 Homeobox domain": "DMBX1",
    "DMTF1 SANT/Myb domain": "DMTF1",
    "DNAJB11 DnaJ domain": "DNAJB11",
    "DNAJB1 DnaJ domain": "DNAJB1",
    "DNAJB5 DnaJ domain": "DNAJB5",
    "DNAJB7 DnaJ domain": "DNAJB7",
    "DNAJC1 SANT/Myb domain": "DNAJC1",
    "DNAJC21 Zinc finger, double-stranded RNA binding domain": "DNAJC21",
    "DNAJC2 SANT/Myb domain": "DNAJC2",
    "DNAJC5 DnaJ domain": "DNAJC5",
    "DNAJC7 DnaJ domain": "DNAJC7",
    "DNMBP SH3 domain": "DNMBP",
    "DPH3 DPH-type metal-binding domain": "DPH3",
    "DTNA Zinc finger, ZZ-type domain": "DTNA",
    "DVL1 DIX domain": "DVL1",
    "DVL1 PDZ domain": "DVL1",
    "DVL3 DIX domain": "DVL3",
    "ELF3 Pointed domain": "ELF3",
    "ELF5 Pointed domain": "ELF5",
    "ELOF1 Transcription elongation factor 1": "ELOF1",
    "EP300 Coactivator CBP, KIX domain": "EP300",
    "EPRS1 WHEP-TRS domain": "EPRS1",
    "EPS8 SAM domain": "EPS8",
    "EPS8 SH3 domain": "EPS8",
    "ERBIN PDZ domain": "ERBIN",
    "ERG Pointed domain": "ERG",
    "ERI1 SAP domain": "ERI1",
    "ESRRB Zinc finger, nuclear hormone receptor-type domain": "ESRRB",
    "ETS1 Pointed domain": "ETS1",
    "FADD Death effector domain": "FADD",
    "FANCL FANCL C-terminal domain": "FANCL",
    "FBXO11 Zinc finger, UBR-type domain": "FBXO11",
    "FBXO22 F-box domain": "FBXO22",
    "FCHSD1 SH3 domain": "FCHSD1",
    "FEZF1 Zinc finger C2H2-type domain": "FEZF1",
    "FHL1 Zinc finger, LIM-type domain": "FHL1",
    "FHL2 Zinc finger, LIM-type domain": "FHL2",
    "FLI1 Pointed domain": "FLI1",
    "FLNB Filamin/ABP280 repeat-like domain": "FLNB",
    "FMR1 K Homology domain, type 1": "FMR1",
    "FNBP4 WW domain": "FNBP4",
    "FRMPD4 PDZ domain": "FRMPD4",
    "FUBP1 K Homology domain, type 1": "FUBP1",
    "FUBP3 K Homology domain, type 1": "FUBP3",
    "GABPA Pointed domain": "GABPA",
    "GAS2L1 GAR domain": "GAS2L1",
    "GATAD2B Zinc finger, GATA-type domain": "GATAD2B",
    "GFI1B Zinc finger C2H2-type domain": "GFI1B",
    "GFI1 Zinc finger C2H2-type domain": "GFI1",
    "GLI1 Zinc finger C2H2-type domain": "GLI1",
    "GLI2 Zinc finger C2H2-type domain": "GLI2",
    "GLI3 Zinc finger C2H2-type domain": "GLI3",
    "GLIS3 Zinc finger C2H2-type domain": "GLIS3",
    "GRB2 SH3 domain": "GRB2",
    "GRIP1 PDZ domain": "GRIP1",
    "GRLF1 FF domain": "ARHGAP35",
    "GSC Homeobox domain": "GSC",
    "GSX2 Homeobox domain": "GSX2",
    "GTF2F2 TFIIF beta subunit, HTH domain": "GTF2F2",
    "H1-6 Linker histone H1/H5, domain H15": "H1-6",
    "HARS1 WHEP-TRS domain": "HARS1",
    "HCK SH3 domain": "HCK",
    "HECTD1 FKBP3, basic tilted helix bundle domain": "HECTD1",
    "HECW2 WW domain": "HECW2",
    "HERC2 CPH domain": "HERC2",
    "HESX1 Homeobox domain": "HESX1",
    "HMG20A High mobility group box domain": "HMG20A",
    "HNRNPK K Homology domain, type 1": "HNRNPK",
    "HNRNPUL1 SAP domain": "HNRNPUL1",
    "HNRNPUL2 SAP domain": "HNRNPUL2",
    "HNRNPU SAP domain": "HNRNPU",
    "HOXB1 Homeobox domain": "HOXB1",
    "HUWE1 Ubiquitin-associated domain": "HUWE1",
    "INTS12 Zinc finger, PHD-finger domain": "INTS12",
    "ITCH WW domain": "ITCH",
    "ITK SH3 domain": "ITK",
    "ITSN1 SH3 domain": "ITSN1",
    "ITSN2 SH3 domain": "ITSN2",
    "KANSL2 Potential DNA-binding domain": "KANSL2",
    "KCMF1 Drought induced 19 protein type, zinc-binding domain": "KCMF1",
    "KDM1A SWIRM domain": "KDM1A",
    "KDM1B Zinc finger, CW-type domain": "KDM1B",
    "KDM2B Zinc finger, PHD-finger domain": "KDM2B",
    "KDM5C Zinc finger, PHD-finger domain": "KDM5C",
    "KHSRP K Homology domain, type 1": "KHSRP",
    "KIF16B Phox homology domain": "KIF16B",
    "KLF11 Zinc finger C2H2-type domain": "KLF11",
    "KMT2A Zinc finger, CXXC-type domain": "KMT2A",
    "LATS1 Ubiquitin-associated domain": "LATS1",
    "LCK SH3 domain": "LCK",
    "LCOR DNA binding HTH domain, Psq-type": "LCOR",
    "LCP1 EF-hand domain": "LCP1",
    "LDB3 PDZ domain": "LDB3",
    "LIMS2 Zinc finger, LIM-type domain": "LIMS2",
    "LSM14A Lsm14-like, N-terminal domain": "LSM14A",
    "MAEL High mobility group box domain": "MAEL",
    "MAGI1 WW domain": "MAGI1",
    "MAGI2 PDZ domain": "MAGI2",
    "MAGI2 WW domain": "MAGI2",
    "MAGI3 WW domain": "MAGI3",
    "MAMSTR SAP domain": "MAMSTR",
    "MAP2K5 PB1 domain": "MAP2K5",
    "MAP3K20 Sterile alpha motif domain": "MAP3K20",
    "MCM10 Zinc finger, Mcm10/DnaG-type domain": "MCM10",
    "MDM2 Zinc finger, RanBP2-type domain": "MDM2",
    "MDM4 Zinc finger, RanBP2-type domain": "MDM4",
    "MECP2 Methyl-CpG DNA binding domain": "MECP2",
    "MEX3C K Homology domain, type 1": "MEX3C",
    "MEX3D K Homology domain, type 1": "MEX3D",
    "MIB1 Mind bomb, SH3 repeat domain": "MIB1",
    "MID1 B-box-type zinc finger domain": "MID1",
    "MID2 B-box-type zinc finger domain": "MID2",
    "MIS18BP1 SANT/Myb domain": "MIS18BP1",
    "MKRN1 Zinc finger, CCCH-type domain": "MKRN1",
    "MKRN2 Zinc finger, CCCH-type domain": "MKRN2",
    "MPDZ PDZ domain": "MPDZ",
    "MPP3 PDZ domain": "MPP3",
    "MRTFA SAP domain": "MRTFA",
    "MSX1 Homeobox domain": "MSX1",
    "MSX2 Homeobox domain": "MSX2",
    "MTA3 SANT/Myb domain": "MTA3",
    "MXD1 Myc-type, basic helix-loop-helix (bHLH) domain": "MXD1",
    "MXI1 Myc-type, basic helix-loop-helix (bHLH) domain": "MXI1",
    "MYB SANT/Myb domain": "MYB",
    "MYO1E SH3 domain": "MYO1E",
    "MYOCD SAP domain": "MYOCD",
    "MYSM1 SANT/Myb domain": "MYSM1",
    "NANOS2 Zinc finger, nanos-type domain": "NANOS2",
    "NA Transcription factor IIS, N-terminal domain": "TCEA1",
    "NA Ubiquitin-like domain": "unknown",
    "NCF1 SH3 domain": "NCF1",
    "NCF2 PB1 domain": "NCF2",
    "NCF2 SH3 domain": "NCF2",
    "NCOR2 SANT/Myb domain": "NCOR2",
    "NEB SH3 domain": "NEB",
    "NEDD4L WW domain": "NEDD4L",
    "NEDD4 WW domain": "NEDD4",
    "NEIL3 Zinc finger, RanBP2-type domain": "NEIL3",
    "NPHP1 SH3 domain": "NPHP1",
    "NR1D2 Zinc finger, nuclear hormone receptor-type domain": "NR1D2",
    "NR2F1 Zinc finger, nuclear hormone receptor-type domain": "NR2F1",
    "NR3C1 Zinc finger, nuclear hormone receptor-type domain": "NR3C1",
    "NR3C2 Zinc finger, nuclear hormone receptor-type domain": "NR3C2",
    "NR4A2 Zinc finger, nuclear hormone receptor-type domain": "NR4A2",
    "OTX2 Homeobox domain": "OTX2",
    "OVOL2 Zinc finger C2H2-type domain": "OVOL2",
    "PACSIN1 SH3 domain": "PACSIN1",
    "PACSIN2 SH3 domain": "PACSIN2",
    "PACSIN3 SH3 domain": "PACSIN3",
    "PARD3B PDZ domain": "PARD3B",
    "PARD3 PDZ domain": "PARD3",
    "PAX6 Homeobox domain": "PAX6",
    "PAX7 Homeobox domain": "PAX7",
    "PBRM1 High mobility group box domain": "PBRM1",
    "PCBP1 K Homology domain, type 1": "PCBP1",
    "PCLO Zinc finger, piccolo-type domain": "PCLO",
    "PDHX Peripheral subunit-binding domain": "PDHX",
    "PDLIM2 Zinc finger, LIM-type domain": "PDLIM2",
    "PDZRN3 PDZ domain": "PDZRN3",
    "PHOX2A Homeobox domain": "PHOX2A",
    "PKN1 HR1 rho-binding domain": "PKN1",
    "PLCG2 SH3 domain": "PLCG2",
    "PMS1 High mobility group box domain": "PMS1",
    "POU1F1 POU-specific domain": "POU1F1",
    "POU2F1 POU-specific domain": "POU2F1",
    "POU2F2 POU-specific domain": "POU2F2",
    "POU2F3 POU-specific domain": "POU2F3",
    "POU3F1 POU-specific domain": "POU3F1",
    "POU3F2 Homeobox domain": "POU3F2",
    "POU3F2 POU-specific domain": "POU3F2",
    "POU3F3 Homeobox domain": "POU3F3",
    "POU3F3 POU-specific domain": "POU3F3",
    "POU3F4 Homeobox domain": "POU3F4",
    "POU4F1 POU-specific domain": "POU4F1",
    "POU4F2 POU-specific domain": "POU4F2",
    "POU4F3 POU-specific domain": "POU4F3",
    "POU5F1 POU-specific domain": "POU5F1",
    "POU6F1 POU-specific domain": "POU6F1",
    "POU6F2 Homeobox domain": "POU6F2",
    "PPARD Zinc finger, nuclear hormone receptor-type domain": "PPARD",
    "PPP1R9A Sterile alpha motif domain": "PPP1R9A",
    "PRDM15 Zinc finger C2H2-type domain": "PRDM15",
    "PRDM16 Zinc finger C2H2-type domain": "PRDM16",
    "PRDM5 Zinc finger C2H2-type domain": "PRDM5",
    "PRDM8 Zinc finger C2H2-type domain": "PRDM8",
    "PRKCD Protein kinase C-like, phorbol ester/diacylglycerol-binding domain": "PRKCD",
    "PROP1 Homeobox domain": "PROP1",
    "PRPF3 PWI domain": "PRPF3",
    "PRPF40A FF domain": "PRPF40A",
    "PRPF40A WW domain": "PRPF40A",
    "PRPF40B FF domain": "PRPF40B",
    "PRRX1 Homeobox domain": "PRRX1",
    "PSTPIP1 SH3 domain": "PSTPIP1",
    "PYCARD CARD domain": "PYCARD",
    "RAD23B Ubiquitin-associated domain": "RAD23B",
    "RAF1 Raf-like Ras-binding domain": "RAF1",
    "RAG2 Recombination activating protein 2, PHD domain": "RAG2",
    "RANBP2 Zinc finger, RanBP2-type domain": "RANBP2",
    "RARB Zinc finger, nuclear hormone receptor-type domain": "RARB",
    "RASA1 SH3 domain": "RASA1",
    "RASA4 Zinc finger, Btk motif domain": "RASA4",
    "RASGRP1 Protein kinase C-like, phorbol ester/diacylglycerol-binding domain": "RASGRP1",
    "RBCK1 IBR domain": "RBCK1",
    "RBM10 Zinc finger, RanBP2-type domain": "RBM10",
    "RCOR1 SANT/Myb domain": "RCOR1",
    "RCOR3 SANT/Myb domain": "RCOR3",
    "RERE Zinc finger, GATA-type domain": "RERE",
    "RFC1 BRCT domain": "RFC1",
    "RIPK2 CARD domain": "RIPK2",
    "RNF113A Zinc finger, CCCH-type domain": "RNF113A",
    "RNF126 E3 ubiquitin-protein ligase RNF126-like, zinc-ribbon domain": "RNF126",
    "RNF32 IQ motif, EF-hand binding site domain": "RNF32",
    "RNF7 Zinc finger, RING-H2-type domain": "RNF7",
    "RPL35 Ribosomal protein L29/L35": "RPL35",
    "RSL24D1 Ribosomal protein L24e-related": "RSL24D1",
    "RUFY1 FYVE zinc finger domain": "RUFY1",
    "RXRA Zinc finger, nuclear hormone receptor-type domain": "RXRA",
    "SAFB2 SAP domain": "SAFB2",
    "SAFB SAP domain": "SAFB",
    "SALL1 Zinc finger C2H2-type domain": "SALL1",
    "SALL4 Zinc finger C2H2-type domain": "SALL4",
    "SAMD9 Sterile alpha motif domain": "SAMD9",
    "SARNP SAP domain": "SARNP",
    "SASH1 Sterile alpha motif domain": "SASH1",
    "SATB1 CUT domain": "SATB1",
    "SATB1 SATB, CUT1-like DNA-binding domain": "SATB1",
    "SATB2 CUT domain": "SATB2",
    "SCRIB PDZ domain": "SCRIB",
    "SETD2 WW domain": "SETD2",
    "SH3D19 SH3 domain": "SH3D19",
    "SH3PXD2B SH3 domain": "SH3PXD2B",
    "SHOX Homeobox domain": "SHOX",
    "SHROOM4 PDZ domain": "SHROOM4",
    "SIX1 Homeobox domain": "SIX1",
    "SIX2 Homeobox domain": "SIX2",
    "SIX3 Homeobox domain": "SIX3",
    "SIX6 Homeobox domain": "SIX6",
    "SLTM SAP domain": "SLTM",
    "SMARCA4 BRK domain": "SMARCA4",
    "SMARCB1 SNF5/SMARCB1/INI1 domain": "SMARCB1",
    "SMARCC1 SANT/Myb domain": "SMARCC1",
    "SMARCC2 SANT/Myb domain": "SMARCC2",
    "SMARCE1 High mobility group box domain": "SMARCE1",
    "SMURF2 WW domain": "SMURF2",
    "SNTA1 PDZ domain": "SNTA1",
    "SOX11 High mobility group box domain": "SOX11",
    "SOX17 High mobility group box domain": "SOX17",
    "SOX18 High mobility group box domain": "SOX18",
    "SOX2 High mobility group box domain": "SOX2",
    "SOX30 High mobility group box domain": "SOX30",
    "SOX3 High mobility group box domain": "SOX3",
    "SOX4 High mobility group box domain": "SOX4",
    "SOX5 High mobility group box domain": "SOX5",
    "SOX6 High mobility group box domain": "SOX6",
    "SOX8 High mobility group box domain": "SOX8",
    "SP7 Zinc finger C2H2-type domain": "SP7",
    "SPTA1 SH3 domain": "SPTA1",
    "SPTAN1 EF-hand domain": "SPTAN1",
    "SQSTM1 Sequestosome-1, UBA domain": "SQSTM1",
    "SQSTM1 Zinc finger, ZZ-type domain": "SQSTM1",
    "SRC SH3 domain": "SRC",
    "SRGAP1 SH3 domain": "SRGAP1",
    "SRGAP3 SH3 domain": "SRGAP3",
    "SRY High mobility group box domain": "SRY",
    "STAU1 Double-stranded RNA-binding domain": "STAU1",
    "STOX1 Storkhead-box protein, winged-helix domain": "STOX1",
    "STOX2 Storkhead-box protein, winged-helix domain": "STOX2",
    "STXBP4 WW domain": "STXBP4",
    "SUOX Cytochrome b5-like heme/steroid binding domain": "SUOX",
    "TAB3 Ubiquitin system component CUE domain": "TAB3",
    "TADA2A SWIRM domain": "TADA2A",
    "TARDBP TAR DNA-binding protein 43, N-terminal domain": "TARDBP",
    "TAX1BP1 CALCOCO1/2, zinc finger UBZ1-type domain": "TAX1BP1",
    "TCEANC Transcription factor IIS, N-terminal domain": "TCEANC",
    "TCERG1 FF domain": "TCERG1",
    "TCERG1L FF domain": "TCERG1L",
    "TDRD3 Tudor domain": "TDRD3",
    "TERF2 SANT/Myb domain": "TERF2",
    "TESMIN CRC domain": "TESMIN",
    "TFG PB1 domain": "TFG",
    "TIAM1 PDZ domain": "TIAM1",
    "TJP2 PDZ domain": "TJP2",
    "TNNC2 EF-hand domain": "TNNC2",
    "TOE1 Zinc finger, CCCH-type domain": "TOE1",
    "TOP3A Zinc finger, GRF-type domain": "TOP3A",
    "TOX3 High mobility group box domain": "TOX3",
    "TP63 Sterile alpha motif domain": "TP63",
    "TP73 Sterile alpha motif domain": "TP73",
    "TRIM26 B-box-type zinc finger domain": "TRIM26",
    "TRIM28 Zinc finger, PHD-finger domain": "TRIM28",
    "TRIM36 B-box-type zinc finger domain": "TRIM36",
    "TRIM3 B-box-type zinc finger domain": "TRIM3",
    "TRIM44 B-box-type zinc finger domain": "TRIM44",
    "TRIM49C B-box-type zinc finger domain": "TRIM49C",
    "TRIM6 B-box-type zinc finger domain": "TRIM6",
    "TRIM71 B-box-type zinc finger domain": "TRIM71",
    "TRMT13 Zinc finger, CCCH-type, TRM13 domain": "TRMT13",
    "TTC3 Zinc finger, RING-type domain": "TTC3",
    "UBE2K Ubiquitin-associated domain": "UBE2K",
    "UBE3A Ubiquitin-protein ligase E3A, N-terminal zinc-binding domain": "UBE3A",
    "UBE4B U box domain": "UBE4B",
    "UBQLN3 Ubiquitin-associated domain": "UBQLN3",
    "UBTF High mobility group box domain": "UBTF",
    "UBXN2B UBX domain": "UBXN2B",
    "UFM1 Ubiquitin-fold modifier 1": "UFM1",
    "USH1C PDZ domain": "USH1C",
    "VAV1 SH3 domain": "VAV1",
    "VAX1 Homeobox domain": "VAX1",
    "VCP CDC48, N-terminal subdomain": "VCP",
    "VIL1 Villin headpiece domain": "VIL1",
    "WBP4 U1-C, C2H2-type zinc finger domain": "WBP4",
    "WNK1 Serine/threonine-protein kinase OSR1/WNK, CCT domain": "WNK1",
    "WSB2 SOCS box domain": "WSB2",
    "WWP1 WW domain": "WWP1",
    "WWP2 WW domain": "WWP2",
    "WWTR1 WW domain": "WWTR1",
    "XRCC6 SAP domain": "XRCC6",
    "YAP1 WW domain": "YAP1",
    "YBX1 Cold-shock protein, DNA-binding domain": "YBX1",
    "YBX2 Cold-shock protein, DNA-binding domain": "YBX2",
    "YBX3 Cold-shock protein, DNA-binding domain": "YBX3",
    "YY1 Zinc finger C2H2-type domain": "YY1",
    "ZBTB20 Zinc finger C2H2-type domain": "ZBTB20",
    "ZBTB24 Zinc finger C2H2-type domain": "ZBTB24",
    "ZC3H10 Zinc finger, CCCH-type domain": "ZC3H10",
    "ZC3H15 E3 ligase, CCCH-type zinc finger domain": "ZC3H15",
    "ZC3H7A Zinc finger, CCCH-type domain": "ZC3H7A",
    "ZEB1 Zinc finger C2H2-type domain": "ZEB1",
    "ZFC3H1 Putative zinc-finger domain": "ZFC3H1",
    "ZFHX2 Homeobox domain": "ZFHX2",
    "ZFHX3 Homeobox domain": "ZFHX3",
    "ZFHX4 Homeobox domain": "ZFHX4",
    "ZFP30 Zinc finger C2H2-type domain": "ZFP30",
    "ZFP36L2 Zinc finger, CCCH-type domain": "ZFP36L2",
    "ZFP36 Zinc finger, CCCH-type domain": "ZFP36",
    "ZFP57 Zinc finger C2H2-type domain": "ZFP57",
    "ZFYVE16 FYVE zinc finger domain": "ZFYVE16",
    "ZHX1 ZHX, C2H2 finger domain": "ZHX1",
    "ZIC2 ZIC protein, zinc finger domain": "ZIC2",
    "ZIC3 Zinc finger C2H2-type domain": "ZIC3",
    "ZMAT3 Zinc finger, double-stranded RNA binding domain": "ZMAT3",
    "ZMYM2 Zinc finger, MYM-type domain": "ZMYM2",
    "ZMYM3 Zinc finger, MYM-type domain": "ZMYM3",
    "ZMYM5 Zinc finger, MYM-type domain": "ZMYM5",
    "ZMYM6 Zinc finger, MYM-type domain": "ZMYM6",
    "ZNF148 Zinc finger C2H2-type domain": "ZNF148",
    "ZNF292 Zinc finger C2H2-type domain": "ZNF292",
    "ZNF408 Zinc finger C2H2-type domain": "ZNF408",
    "ZNF711 Zinc finger C2H2-type domain": "ZNF711",
    "ZNF81 Zinc finger C2H2-type domain": "ZNF81",
    "ZRANB2 Zinc finger, RanBP2-type domain": "ZRANB2",
    "ZYX Zinc finger, LIM-type domain": "ZYX",
    "ZZZ3 SANT/Myb domain": "ZZZ3",
}
