tissue_mapping = {
    "Adrenocortical Carcinoma": "adrenal gland",
    "Ampullary Carcinoma": "hepatopancreatic ampulla",
    "Gallbladder Adenocarcinoma, NOS": "biliary system",
    "Intrahepatic Cholangiocarcinoma": "biliary system",
    "Extrahepatic Cholangiocarcinoma": "biliary system",
    "Immortalized Cholangiocyte, Highly Differentiated": "biliary system",
    "Gallbladder Cancer": "biliary system",
    "Cholangiocarcinoma": "biliary system",
    "Bladder Urothelial Carcinoma": "urinary bladder",
    "Bladder Squamous Cell Carcinoma": "urinary bladder",
    "Urethral Urothelial Carcinoma": "urinary bladder",
    "Ewing Sarcoma": "bone tissue",
    "Osteosarcoma": "bone tissue",
    "Chondrosarcoma": "bone tissue",
    "Dedifferentiated Chondrosarcoma": "bone tissue",
    "Extraskeletal Myxoid Chondrosarcoma": "bone tissue",
    "Chordoma": "bone tissue",
    "Giant Cell Tumor of Bone": "bone tissue",
    "Colon Adenocarcinoma": "intestine",
    "Rectal Adenocarcinoma": "intestine",
    "Duodenal Adenocarcinoma": "intestine",
    "Mucinous Adenocarcinoma of the Colon and Rectum": "intestine",
    "Colorectal Adenocarcinoma": "intestine",
    "High-Grade Neuroendocrine Carcinoma of the Colon and Rectum": "intestine",
    "Invasive Breast Carcinoma": "breast",
    "Breast Invasive Lobular Carcinoma": "breast",
    "Breast Invasive Ductal Carcinoma": "breast",
    "Breast Invasive Carcinoma, NOS": "breast",
    "Breast Ductal Carcinoma In Situ": "breast",
    "Immortalized Breast Cells": "breast",
    "Breast Invasive Cancer, NOS": "breast",
    "Breast Neoplasm, NOS": "breast",
    "Small Cell Neuroendocrine Carcinoma of the Cervix": "uterine cervix",
    "Cervical Squamous Cell Carcinoma": "uterine cervix",
    "Endocervical Adenocarcinoma": "uterine cervix",
    "Mixed Cervical Carcinoma": "uterine cervix",
    "Cervical Adenocarcinoma": "uterine cervix",
    "Glassy Cell Carcinoma of the Cervix": "uterine cervix",
    "Small Cell Carcinoma of the Cervix": "uterine cervix",
    "Meningioma": "central nervous system",
    "Glioblastoma": "central nervous system",
    "Astrocytoma": "central nervous system",
    "Medulloblastoma": "central nervous system",
    "Oligodendroglioma": "central nervous system",
    "Atypical Teratoid/Rhabdoid Tumor": "central nervous system",
    "Gliosarcoma": "central nervous system",
    "Anaplastic Astrocytoma": "central nervous system",
    "Primitive Neuroectodermal Tumor": "central nervous system",
    "Immortalized Epithelial Cells, CNS": "central nervous system",
    "Diffuse Intrinsic Pontine Glioma": "central nervous system",
    "Immortalized Astrocytes": "central nervous system",
    "Immortalized Endothelial Cells, Endoneurial": "central nervous system",
    "Immortalized Neuronal Progenitor Cells": "central nervous system",
    "Immortalized Endothelial Cells, Umbilical Vein": "umbilical vein",
    "Stomach Adenocarcinoma": "stomach",
    "Esophageal Adenocarcinoma": "stomach",
    "Small Cell Carcinoma of the Stomach": "stomach",
    "Tubular Stomach Adenocarcinoma": "stomach",
    "Diffuse Type Stomach Adenocarcinoma": "stomach",
    "Esophageal Squamous Cell Carcinoma": "stomach",
    "Adenosquamous Carcinoma of the Stomach": "stomach",
    "Signet Ring Cell Carcinoma of the Stomach": "stomach",
    "Mucinous Stomach Adenocarcinoma": "stomach",
    "Adenocarcinoma of the Gastroesophageal Junction": "stomach",
    "Retinoblastoma": "eye",
    "Uveal Melanoma": "eye",
    "Immortalized Epithelial Cells, Corneal": "eye",
    "Immortalized Epithelial Cells, Retinal": "eye",
    "Fibroblast, Skin": "skin of body",
    "Fibroblast, Lymphoid": "lymphoid tissue",
    "Fibroblast, Bone": "bone tissue",
    "Fibroblast, Soft Tissue": "soft tissue",
    "Fibroblast, Breast": "breast",
    "Fibroblast, Urinary Tract": "urinary bladder",
    "Fibroblast, Lung": "lung",
    "Fibroblast": None,
    "Fibroblast, Colorectal": "colorectum",
    "Fibroblast, Upper Aerodigestive": "digestive tract",
    "Fibroblast, NOS": None,
    "Immortalized Hair Follicle Inner Root Sheath Cells": "hair follicle",
    "Immortalized Hair Germinal Matrix Cells": "hair follicle",
    "Head and Neck Squamous Cell Carcinoma": "craniocervical region",
    "Oral Cavity Squamous Cell Carcinoma": "oral cavity",
    "Oropharynx Squamous Cell Carcinoma": "oropharynx",
    "Hypopharynx Squamous Cell Carcinoma": "hypopharynx",
    "Larynx Squamous Cell Carcinoma": "larynx",
    "NUT Midline Carcinoma of the Head and Neck": "craniocervical region",
    "Sinonasal Squamous Cell Carcinoma": "craniocervical region",
    "Head and Neck Carcinoma, Other": "craniocervical region",
    "Mucoepidermoid Carcinoma": "craniocervical region",
    "Adenoid Cystic Carcinoma": "pharyngeal tonsil",
    "Renal Clear Cell Carcinoma": "kidney",
    "Papillary Renal Cell Carcinoma": "kidney",
    "Immortalized Embyonic Kidney Cells": "kidney",
    "Rhabdoid Cancer": "kidney",
    "Renal Cell Carcinoma": "kidney",
    "Renal Medullary Carcinoma": "kidney",
    "Wilms\\' Tumor": "kidney",
    "Immortalized Epithelial Cells, Renal": "kidney",
    "Hepatocellular Carcinoma": "liver",
    "Hepatoblastoma": "liver",
    "Hepatocellular Carcinoma plus Intrahepatic Cholangiocarcinoma": "liver",
    "Immortalized Liver Cells": "liver",
    "Lung Adenocarcinoma": "lung",
    "Large Cell Lung Carcinoma": "lung",
    "Non-Small Cell Lung Cancer": "lung",
    "Immortalized Lung Cells": "lung",
    "NUT Carcinoma of the Lung": "lung",
    "Lung Squamous Cell Carcinoma": "lung",
    "Small Cell Lung Cancer": "lung",
    "SMARCA4-deficient undifferentiated tumor": "lung",
    "Lung Adenosquamous Carcinoma": "lung",
    "Giant Cell Carcinoma of the Lung": "lung",
    "Lung Carcinoid": "lung",
    "Mucoepidermoid Carcinoma of the Lung": "lung",
    "Poorly Differentiated Non-Small Cell Lung Cancer": "lung",
    "Immortalized Epithelial Cells, Lung": "lung",
    "Immortalized MPLC Cells": "lung",
    "B-Cell Acute Lymphoblastic Leukemia": "lymphoid tissue",
    "Plasma Cell Myeloma": "lymphoid tissue",
    "Transformed cell line, B lymphoblast": "lymphoid tissue",
    "Anaplastic Large-Cell Lymphoma ALK Positive": "lymphoid tissue",
    "Diffuse Large B-Cell Lymphoma, NOS": "lymphoid tissue",
    "Mature T and NK Neoplasms": "lymphoid tissue",
    "Mantle Cell Lymphoma": "lymphoid tissue",
    "Hodgkin Lymphoma": "lymphoid tissue",
    "T-Cell Acute Lymphoblastic Leukemia": "lymphoid tissue",
    "Activated B-cell Type": "lymphoid tissue",
    "Burkitt Lymphoma": "lymphoid tissue",
    "B-Cell Prolymphocytic Leukemia": "lymphoid tissue",
    "Chronic Lymphocytic Leukemia/Small Lymphocytic Lymphoma": "lymphoid tissue",
    "Sezary Syndrome": "lymphoid tissue",
    "Mature B-Cell Neoplasms": "lymphoid tissue",
    "Mycosis Fungoides": "lymphoid tissue",
    "Non-Hodgkin Lymphoma": "lymphoid tissue",
    "Primary Effusion Lymphoma": "lymphoid tissue",
    "Hepatosplenic T-cell Lymphoma": "lymphoid tissue",
    "Anaplastic Large-Cell Lymphoma ALK Negative": "lymphoid tissue",
    "Natural Killer (NK) Cell Lymphoblastic Leukemia/Lymphoma (NKCLL)": "lymphoid tissue",
    "T-Cell Large Granular Lymphocytic Leukemia": "lymphoid tissue",
    "Follicular T-Cell Lymphoma": "lymphoid tissue",
    "Hairy Cell Leukemia": "lymphoid tissue",
    "Germinal Center B-Cell Type": "lymphoid tissue",
    "Splenic Marginal Zone Lymphoma": "lymphoid tissue",
    "High-Grade B-Cell Lymphoma, with MYC and BCL2 and/or BCL6 Rearrangements": "lymphoid tissue",
    "Follicular Lymphoma": "lymphoid tissue",
    "Matched Normal": "lymphoid tissue",
    "Primary Mediastinal (Thymic) Large B-Cell Lymphoma (PMBL)": "lymphoid tissue",
    "B lymphoblast": "lymphoid tissue",
    "T-Cell Prolymphocytic Leukemia": "lymphoid tissue",
    "Immortalized Cardiomyocytes": "cardiac muscle tissue",
    "immortalized Smooth Muscle Cells, Coronary artery": "smooth muscle tissue",
    "Immortalized Smooth Muscle Cells, Pulmonary artery": "smooth muscle tissue",
    "Immortalized Skeletal Muscle Cells": "skeletal muscle tissue",
    "Immortalized Smooth Muscle Cells, Intestinal": "smooth muscle tissue",
    "AML with Myelodysplasia-Related Changes": "bone marrow",
    "AML, NOS": "bone marrow",
    "Acute Myeloid Leukemia": "bone marrow",
    "Chronic Myeloid Leukemia, BCR-ABL1+": "bone marrow",
    "Acute Monoblastic/Monocytic Leukemia": "bone marrow",
    "Acute Promyelocytic Leukemia": "bone marrow",
    "Myeloid Leukemia Associated with Down Syndrome": "bone marrow",
    "Acute Megakaryoblastic Leukemia": "bone marrow",
    "Acute Leukemias of Ambiguous Lineage": "bone marrow",
    "Immortalized Blood": "bone marrow",
    "Acute Myelomonocytic Leukemia": "bone marrow",
    "Spherocytosis": "bone marrow",
    "AML with Minimal Differentiation": "bone marrow",
    "Transformed cell line": None,
    "Immortalized Human Intervertebral Disc Cartilage Endplate-derived Stem Cells": "intervertebral disk",
    "Immortalized Human Chondrocytes": "cartilage tissue",
    "Immortalized Human Pancreatic Mesenchymal Stem Cells": "pancreas",
    "Immortalized Submandibular Gland Cells": "submandibular gland",
    "Matched Normal": None,
    "Extra Gonadal Germ Cell Tumor": None,
    "High-Grade Serous Ovarian Cancer": "ovary",
    "Endometrioid Ovarian Cancer": "ovary",
    "Serous Ovarian Cancer": "ovary",
    "Small Cell Carcinoma of the Ovary": "ovary",
    "Mucinous Ovarian Cancer": "ovary",
    "Brenner Tumor, Malignant": "ovary",
    "Clear Cell Ovarian Cancer": "ovary",
    "Immortalized Ovarian Cells": "ovary",
    "Mixed Ovarian Carcinoma": "ovary",
    "Mixed Germ Cell Tumor": "ovary",
    "Ovarian Cancer, Other": "ovary",
    "Granulosa Cell Tumor": "ovary",
    "Pancreatic Adenocarcinoma": "pancreas",
    "Adenosquamous Carcinoma of the Pancreas": "pancreas",
    "Pancreatic Neuroendocrine Tumor": "pancreas",
    "Immortalized Pancreatic Stromal Cells": "pancreas",
    "Neuroblastoma": "peripheral nervous system",
    "Malignant Peripheral Nerve Sheath Tumor": "peripheral nervous system",
    "Pleural Mesothelioma, Epithelioid Type": "pleura",
    "Pleural Mesothelioma, Biphasic Type": "pleura",
    "Pleural Mesothelioma, Sarcomatoid Type": "pleura",
    "Pleural Mesothelioma": "pleura",
    "Prostate Adenocarcinoma": "prostate gland",
    "Immortalized Epithelial Cells, Prostate": "prostate gland",
    "Prostate Small Cell Carcinoma": "prostate gland",
    "Immortalized Prostate Cells": "prostate gland",
    "Hyperplasia, Prostate": "prostate gland",
    "Prostate Neuroendocrine Carcinoma": "prostate gland",
    "Melanoma": "skin of body",
    "Cutaneous Melanoma": "skin of body",
    "Merkel Cell Carcinoma": "skin of body",
    "Cutaneous Squamous Cell Carcinoma": "skin of body",
    "Acral Melanoma": "skin of body",
    "Dermatofibrosarcoma Protuberans": "skin of body",
    "Sarcoma, NOS": "soft tissue",
    "Rhabdomyosarcoma": "soft tissue",
    "Fibrosarcoma": "soft tissue",
    "Alveolar Rhabdomyosarcoma": "soft tissue",
    "Leiomyosarcoma": "soft tissue",
    "Embryonal Rhabdomyosarcoma": "soft tissue",
    "Extrarenal Rhabdoid Cancer": "soft tissue",
    "CIC-DUX4 Sarcoma": "soft tissue",
    "Undifferentiated Pleomorphic Sarcoma/Malignant Fibrous Histiocytoma/High-Grade Spindle Cell Sarcoma": "soft tissue",
    "Synovial Sarcoma": "soft tissue",
    "Epithelioid Sarcoma": "soft tissue",
    "Liposarcoma": "soft tissue",
    "Clear Cell Sarcoma": "soft tissue",
    "Well-Differentiated Liposarcoma": "soft tissue",
    "Dedifferentiated Liposarcoma": "soft tissue",
    "Gastrointestinal Stromal Tumor": "soft tissue",
    "Myxoid/Round-Cell Liposarcoma": "soft tissue",
    "Desmoid/Aggressive Fibromatosis": "soft tissue",
    "Pleomorphic Rhabdomyosarcoma": "soft tissue",
    "Myxofibrosarcoma": "soft tissue",
    "Alveolar Soft Part Sarcoma": "soft tissue",
    "Embryonal Carcinoma": "testis",
    "Yolk Sac Tumor": "testis",
    "Teratoma": "testis",
    "Follicular Thyroid Cancer": "thyroid gland",
    "Anaplastic Thyroid Cancer": "thyroid gland",
    "Poorly Differentiated Thyroid Cancer": "thyroid gland",
    "Medullary Thyroid Cancer": "thyroid gland",
    "Papillary Thyroid Cancer": "thyroid gland",
    "Endometrial Carcinoma": "uterus",
    "Uterine Carcinosarcoma/Uterine Malignant Mixed Mullerian Tumor": "uterus",
    "Uterine Clear Cell Carcinoma": "uterus",
    "Uterine Sarcoma/Mesenchymal": "uterus",
    "Endometrial Stromal Sarcoma": "uterus",
    "Uterine Leiomyosarcoma": "uterus",
    "Uterine Adenosquamous Carcinoma": "uterus",
    "Choriocarcinoma": "uterus",
    "Squamous Cell Carcinoma of the Vulva/Vagina": "vagina",
    "Mucosal Melanoma of the Vulva/Vagina": "vagina",
}

sex_mapping = {"Male": "male", "Female": "female", "Unknown": None}

age_mapping = {
    "Pediatric": "child",
    "Fetus": "fetal",
    "Adult": "adult",
    "Unknown": None,
}

disease_mapping = {
    "High-Grade Serous Ovarian Cancer": [
        "High-grade serous ovarian cancer",
        "EFO:1001516",
    ],
    "AML with Myelodysplasia-Related Changes": [
        "acute myeloid leukemia with multilineage dysplasia",
        "MONDO:0019456",
    ],
    "Colon Adenocarcinoma": ["Colon adenocarcinoma", "MONDO:0002271"],
    "AML, NOS": ["acute myeloid leukemia by FAB classification", "MONDO:0015667"],
    "Acute Myeloid Leukemia": ["acute myeloid leukemia", "EFO:0000222"],
    "Melanoma": ["Melanoma", "EFO:0000756"],
    "Bladder Urothelial Carcinoma": [
        "bladder urothelial carcinoma",
        "EFO:0006544",
    ],
    "Lung Adenocarcinoma": ["Lung adenocarcinoma", "C0152013"],
    "Large Cell Lung Carcinoma": ["large cell lung carcinoma", "EFO:0003050"],
    "Renal Clear Cell Carcinoma": ["renal clear cell carcinoma", "EFO:0000349"],
    "Invasive Breast Carcinoma": ["invasive breast carcinoma", "EFO:1000307"],
    "B-Cell Acute Lymphoblastic Leukemia": [
        "B-cell acute lymphoblastic leukemia",
        "EFO:0000094",
    ],
    "Pancreatic Adenocarcinoma": ["pancreatic adenocarcinoma", "EFO:1000044"],
    "Plasma Cell Myeloma": ["plasma cell myeloma", "EFO:0001378"],
    "Meningioma": ["meningioma", "MONDO:0016642"],
    "Glioblastoma": ["Glioblastoma", "EFO:0000326"],
    "Non-Small Cell Lung Cancer": ["Non-small cell lung cancer", "EFO:0003060"],
    "Sarcoma, NOS": ["Sarcoma", "NCIT:C9118"],
    "Transformed cell line, B lymphoblast": ["healthy", None],
    "Ewing Sarcoma": ["Ewing sarcoma", "EFO:0000174"],
    "Astrocytoma": ["astrocytoma", "EFO:0000272"],
    "Fibroblast, Skin": ["healthy", None],
    "Breast Invasive Lobular Carcinoma": [
        "invasive ductal and invasive lobular breast carcinoma",
        "EFO:0000552",
    ],
    "Papillary Renal Cell Carcinoma": [
        "papillary renal cell carcinoma",
        "EFO:0000640",
    ],
    "Stomach Adenocarcinoma": ["stomach adenocarcinoma", "EFO:0000503"],
    "Endometrioid Ovarian Cancer": ["Endometrioid ovarian cancer", "EFO:1001515"],
    "Immortalized Embyonic Kidney Cells": ["healthy", None],
    "Rhabdomyosarcoma": ["Rhabdomyosarcoma", "MONDO:0005212"],
    "Anaplastic Large-Cell Lymphoma ALK Positive": [
        "ALK-positive anaplastic large cell lymphoma",
        "MONDO:0017602",
    ],
    "Fibrosarcoma": ["fibrosarcoma", "EFO:0002087"],
    "Medulloblastoma": ["medulloblastoma", "EFO:0002939"],
    "Diffuse Large B-Cell Lymphoma, NOS": [
        "liver diffuse large B-cell lymphoma",
        "MONDO:0006268",
    ],
    "Follicular Thyroid Cancer": [
        "thyroid gland follicular carcinoma",
        "MONDO:0005034",
    ],
    "Mature T and NK Neoplasms": [
        "neoplasm of mature T-cells or NK-cells",
        "MONDO:0005169",
    ],
    "Fibroblast, Lymphoid": ["healthy", None],
    "Immortalized Lung Cells": ["healthy", None],
    "Oligodendroglioma": ["oligodendroglioma", "EFO:0000632"],
    "Mantle Cell Lymphoma": ["Mantle cell lymphoma", "EFO:1001469"],
    "Hodgkin Lymphoma": ["hodgkin lymphoma", "EFO:0000183"],
    "Fibroblast, Bone": ["healthy", None],
    "Chronic Myeloid Leukemia, BCR-ABL1+": [
        "leukemia, myeloid, accelerated-phase",
        "MONDO:0021367",
    ],
    "Neuroblastoma": ["Neuroblastoma", "MONDO:0005072"],
    "Fibroblast, Soft Tissue": ["healthy", None],
    "Acute Monoblastic/Monocytic Leukemia": [
        "acute monocytic leukemia",
        "MONDO:0007896",
    ],
    "Osteosarcoma": ["Osteosarcoma", "EFO:0000637"],
    "Fibroblast, Breast": ["healthy", None],
    "Pleural Mesothelioma, Epithelioid Type": [
        "pleural epithelioid mesothelioma",
        "MONDO:0006378",
    ],
    "Fibroblast, Urinary Tract": ["healthy", None],
    "Prostate Adenocarcinoma": ["prostate adenocarcinoma", "EFO:0000673"],
    "Serous Ovarian Cancer": ["ovarian serous carcinoma", "EFO:1001516"],
    "Pleural Mesothelioma, Biphasic Type": [
        "pleural biphasic mesothelioma",
        "MONDO:0006377",
    ],
    "Rhabdoid Cancer": ["rhabdoid tumor", "MONDO:0002728"],
    "Breast Invasive Ductal Carcinoma": [
        "invasive breast ductal carcinoma",
        "EFO:0000186",
    ],
    "Alveolar Rhabdomyosarcoma": ["alveolar rhabdomyosarcoma", "EFO:0000248"],
    "T-Cell Acute Lymphoblastic Leukemia": [
        "T-cell acute lymphoblastic leukemia",
        "MONDO:0004963",
    ],
    "Adenosquamous Carcinoma of the Pancreas": [
        "pancreatic adenosquamous carcinoma",
        "MONDO:0005614",
    ],
    "Small Cell Carcinoma of the Ovary": [
        "Ovarian Small Cell Carcinoma",
        "EFO:1000431",
    ],
    "Small Cell Neuroendocrine Carcinoma of the Cervix": [
        "cervical small cell carcinoma",
        "MONDO:0006142",
    ],
    "Fibroblast, Lung": ["healthy", None],
    "Fibroblast": ["healthy", None],
    "Gallbladder Adenocarcinoma, NOS": [
        "gallbladder adenocarcinoma",
        "MONDO:0006215",
    ],
    "NUT Carcinoma of the Lung": ["lung sarcomatoid carcinoma", "MONDO:0006279"],
    "Leiomyosarcoma": ["leiomyosarcoma", "EFO:0000564"],
    "Breast Invasive Carcinoma, NOS": [
        "invasive breast carcinoma",
        "MONDO:0006256",
    ],
    "Pleural Mesothelioma, Sarcomatoid Type": [
        "pleural sarcomatoid mesothelioma",
        "MONDO:0006380",
    ],
    "Activated B-cell Type": [
        "diffuse large B-cell lymphoma activated B-cell type",
        "MONDO:0850418",
    ],
    "Atypical Teratoid/Rhabdoid Tumor": [
        "atypical teratoid/rhabdoid tumor",
        "EFO:1002008",
    ],
    "Burkitt Lymphoma": ["Burkitt lymphoma", "MONDO:0007243"],
    "Head and Neck Squamous Cell Carcinoma": [
        "head and neck squamous cell carcinoma",
        "EFO:0000181",
    ],
    "Embryonal Rhabdomyosarcoma": ["embryonal rhabdomyosarcoma", "EFO:0000437"],
    "Immortalized Epithelial Cells, Prostate": ["healthy", None],
    "Renal Cell Carcinoma": ["renal cell carcinoma", "EFO:0000681"],
    "Extrarenal Rhabdoid Cancer": ["extrarenal rhabdoid tumor", "MONDO:0044916"],
    "Endometrial Carcinoma": ["endometrial carcinoma", "EFO:1001512"],
    "Anaplastic Thyroid Cancer": [
        "thyroid gland undifferentiated (anaplastic) carcinoma",
        "MONDO:0006468",
    ],
    "Lung Squamous Cell Carcinoma": [
        "lung squamous cell carcinoma",
        "EFO:0000708",
    ],
    "Prostate Small Cell Carcinoma": [
        "Prostate Small Cell Carcinoma",
        "EFO:1000499",
    ],
    "Small Cell Lung Cancer": ["small cell lung cancer", "EFO:0000702"],
    "Oral Cavity Squamous Cell Carcinoma": [
        "oral cavity squamous cell carcinoma",
        "EFO:0000199",
    ],
    "Ampullary Carcinoma": ["carcinoma of the ampulla of vater", "MONDO:0017590"],
    "Fibroblast, Colorectal": ["healthy", None],
    "Oropharynx Squamous Cell Carcinoma": [
        "oropharynx squamous cell carcinoma",
        "MONDO:0044704",
    ],
    "Intrahepatic Cholangiocarcinoma": [
        "Intrahepatic cholangiocarcinoma",
        "C0345905",
    ],
    "Esophageal Adenocarcinoma": ["Esophageal adenocarcinoma", "EFO:0000478"],
    "Hepatocellular Carcinoma": ["hepatocellular carcinoma", "EFO:0000182"],
    "Small Cell Carcinoma of the Stomach": [
        "gastric small cell neuroendocrine carcinoma",
        "MONDO:0006229",
    ],
    "Mucinous Ovarian Cancer": ["mucinous ovarian cancer", "MONDO:0024282"],
    "Tubular Stomach Adenocarcinoma": [
        "gastric tubular adenocarcinoma",
        "MONDO:0006035",
    ],
    "Diffuse Type Stomach Adenocarcinoma": [
        "diffuse gastric adenocarcinoma",
        "MONDO:0005017",
    ],
    "Extrahepatic Cholangiocarcinoma": [
        "Extrahepatic cholangiocarcinoma",
        "MONDO:0003090",
    ],
    "Gliosarcoma": ["gliosarcoma", "EFO:1001465"],
    "Brenner Tumor, Malignant": [
        "malignant ovarian Brenner tumor",
        "EFO:1000357",
    ],
    "Fibroblast, Upper Aerodigestive": ["healthy", None],
    "Rectal Adenocarcinoma": ["rectal adenocarcinoma", "EFO:0005631"],
    "SMARCA4-deficient undifferentiated tumor": [
        "SMARCA4-deficient sarcoma of thorax",
        "MONDO:0018761",
    ],
    "Acute Promyelocytic Leukemia": [
        "acute promyelocytic leukemia",
        "EFO:0000224",
    ],
    "Uterine Carcinosarcoma/Uterine Malignant Mixed Mullerian Tumor": [
        "uterine carcinosarcoma",
        "MONDO:0006485",
    ],
    "Esophageal Squamous Cell Carcinoma": [
        "esophageal squamous cell carcinoma",
        "EFO:0005922",
    ],
    "Clear Cell Ovarian Cancer": ["Ovarian clear cell cancer", "EFO:1000042"],
    "B-Cell Prolymphocytic Leukemia": [
        "B-cell prolymphocytic leukemia",
        "EFO:1000102",
    ],
    "Pancreatic Neuroendocrine Tumor": [
        "functional pancreatic neuroendocrine tumor",
        "MONDO:0023206",
    ],
    "Breast Ductal Carcinoma In Situ": [
        "breast ductal carcinoma in situ",
        "EFO:0000432",
    ],
    "Adenosquamous Carcinoma of the Stomach": [
        "gastric adenosquamous carcinoma",
        "MONDO:0006034",
    ],
    "Lung Adenosquamous Carcinoma": [
        "lung adenosquamous carcinoma",
        "EFO:0000233",
    ],
    "Uterine Clear Cell Carcinoma": [
        "thymus clear cell carcinoma",
        "MONDO:0004475",
    ],
    "Cutaneous Melanoma": ["cutaneous melanoma", "EFO:0000389"],
    "Chronic Lymphocytic Leukemia/Small Lymphocytic Lymphoma": [
        "chronic lymphocytic leukemia/small lymphocytic lymphoma",
        "MONDO:0003864",
    ],
    "Hypopharynx Squamous Cell Carcinoma": [
        "hypopharynx squamous cell carcinoma",
        "MONDO:0044638",
    ],
    "Chondrosarcoma": ["Chondrosarcoma", "MONDO:0008977"],
    "Giant Cell Carcinoma of the Lung": [
        "lung giant cell carcinoma",
        "MONDO:0006275",
    ],
    "Uterine Sarcoma/Mesenchymal": ["uterine corpus sarcoma", "MONDO:0005210"],
    "Poorly Differentiated Thyroid Cancer": [
        "poorly differentiated thyroid gland carcinoma",
        "MONDO:0006382",
    ],
    "Cervical Squamous Cell Carcinoma": [
        "cervical squamous cell carcinoma",
        "EFO:1000172",
    ],
    "Immortalized Ovarian Cells": ["healthy", None],
    "Larynx Squamous Cell Carcinoma": [
        "laryngeal squamous cell carcinoma",
        "MONDO:0005595",
    ],
    "Sezary Syndrome": ["Sezary syndrome", "MONDO:0017844"],
    "Dedifferentiated Chondrosarcoma": [
        "dedifferentiated chondrosarcoma",
        "EFO:0000394",
    ],
    "Duodenal Adenocarcinoma": ["duodenal adenocarcinoma", "EFO:1000223"],
    "Mature B-Cell Neoplasms": ["neoplasm of mature B-cells", "MONDO:0004949"],
    "Mycosis Fungoides": ["mycosis fungoides", "EFO:1001051"],
    "Myeloid Leukemia Associated with Down Syndrome": [
        "myeloid leukemia associated with down syndrome",
        "MONDO:0850271",
    ],
    "Immortalized Breast Cells": ["healthy", None],
    "Non-Hodgkin Lymphoma": ["Non-Hodgkin lymphoma", "MONDO:0018908"],
    "Hepatoblastoma": ["Hepatoblastoma", "MONDO:0018666"],
    "Mixed Ovarian Carcinoma": [
        "ovarian seromucinous carcinoma",
        "MONDO:0004032",
    ],
    "Signet Ring Cell Carcinoma of the Stomach": [
        "signet ring cell gastric adenocarcinoma",
        "MONDO:0006409",
    ],
    "Mucinous Stomach Adenocarcinoma": [
        "mucinous gastric adenocarcinoma",
        "MONDO:0006309",
    ],
    "CIC-DUX4 Sarcoma": ["CIC-rearranged sarcoma", "MONDO:0956989"],
    "Lung Carcinoid": ["lung carcinoid tumor", "EFO:1000037"],
    "Undifferentiated Pleomorphic Sarcoma/Malignant Fibrous Histiocytoma/High-Grade Spindle Cell Sarcoma": [
        "undifferentiated pleomorphic sarcoma",
        "MONDO:0002142",
    ],
    "Bladder Squamous Cell Carcinoma": [
        "bladder squamous cell carcinoma",
        "EFO:1000130",
    ],
    "Anaplastic Astrocytoma": ["anaplastic astrocytoma", "EFO:0002499"],
    "Endometrial Stromal Sarcoma": ["endometrial stromal sarcoma", "EFO:1000919"],
    "Primary Effusion Lymphoma": ["primary effusion lymphoma", "EFO:1000491"],
    "Uterine Leiomyosarcoma": ["uterine leiomyosarcoma", "EFO:1001974"],
    "Uterine Adenosquamous Carcinoma": [
        "cervical adenosquamous carcinoma",
        "MONDO:0006134",
    ],
    "Urethral Urothelial Carcinoma": [
        "urethra transitional cell carcinoma",
        "MONDO:0002836",
    ],
    "Mucinous Adenocarcinoma of the Colon and Rectum": [
        "rectum mucinous adenocarcinoma",
        "MONDO:0002748",
    ],
    "Endocervical Adenocarcinoma": [
        "endocervical adenocarcinoma",
        "MONDO:0000554",
    ],
    "Fibroblast, NOS": ["healthy", None],
    "Merkel Cell Carcinoma": ["Merkel cell carcinoma", "EFO:1001471"],
    "Primitive Neuroectodermal Tumor": [
        "primitive neuroectodermal tumor",
        "EFO:0005235",
    ],
    "Hepatosplenic T-cell Lymphoma": [
        "hepatosplenic T-cell lymphoma",
        "MONDO:0019474",
    ],
    "Anaplastic Large-Cell Lymphoma ALK Negative": [
        "ALK-negative anaplastic large cell lymphoma",
        "MONDO:0017603",
    ],
    "Mucoepidermoid Carcinoma of the Lung": [
        "pulmonary mucoepidermoid carcinoma",
        "MONDO:0005616",
    ],
    "Transformed cell line": ["healthy", None],
    "Natural Killer (NK) Cell Lymphoblastic Leukemia/Lymphoma (NKCLL)": [
        "aggressive NK-cell leukemia",
        "MONDO:0019470",
    ],
    "T-Cell Large Granular Lymphocytic Leukemia": [
        "T-cell large granular lymphocyte leukemia",
        "MONDO:0019469",
    ],
    "Immortalized Epithelial Cells, CNS": ["healthy", None],
    "Follicular T-Cell Lymphoma": ["follicular lymphoma", "MONDO:0018906"],
    "Renal Medullary Carcinoma": ["kidney medullary carcinoma", "MONDO:0006260"],
    "Acute Megakaryoblastic Leukemia": [
        "acute megakaryoblastic leukemia",
        "EFO:0003025",
    ],
    "Synovial Sarcoma": ["synovial sarcoma", "EFO:0001376"],
    "Retinoblastoma": ["retinoblastoma", "MONDO:0008380"],
    "Medullary Thyroid Cancer": [
        "medullary thyroid gland carcinoma",
        "MONDO:0015277",
    ],
    "Cutaneous Squamous Cell Carcinoma": [
        "Cutaneous squamous cell carcinoma",
        "EFO:1001927",
    ],
    "Mixed Cervical Carcinoma": ["cervical carcinosarcoma", "MONDO:0002877"],
    "Mixed Germ Cell Tumor": ["mixed germ cell tumor", "MONDO:0015864"],
    "Immortalized Prostate Cells": ["healthy", None],
    "NUT Midline Carcinoma of the Head and Neck": [
        "Head and Neck NUT Carcinoma",
        "NCIT:C173087",
    ],
    "Breast Invasive Cancer, NOS": ["invasive breast carcinoma", "MONDO:0006256"],
    "Squamous Cell Carcinoma of the Vulva/Vagina": [
        "vaginal squamous cell carcinoma",
        "MONDO:0006490",
    ],
    "Adrenocortical Carcinoma": ["adrenocortical carcinoma", "EFO:1000796"],
    "Wilms' Tumor": ["Wilms tumor", "MONDO:0006058"],
    "Epithelioid Sarcoma": ["epithelioid sarcoma", "MONDO:0017387"],
    "Embryonal Carcinoma": ["embryonal carcinoma", "EFO:0004986"],
    "Yolk Sac Tumor": ["yolk sac tumor", "MONDO:0005744"],
    "Uveal Melanoma": ["Uveal melanoma", "EFO:1000616"],
    "Hairy Cell Leukemia": ["hairy cell leukemia", "EFO:1000956"],
    "Hyperplasia, Prostate": ["healthy", None],
    "Colorectal Adenocarcinoma": ["colorectal adenocarcinoma", "EFO:0000365"],
    "Adenocarcinoma of the Gastroesophageal Junction": [
        "gastroesophageal junction adenocarcinoma",
        "MONDO:0003219",
    ],
    "Germinal Center B-Cell Type": [
        "diffuse large B-cell lymphoma germinal center B-cell type",
        "MONDO:0850419",
    ],
    "Teratoma": ["Teratoma", "MONDO:0002601"],
    "Extraskeletal Myxoid Chondrosarcoma": [
        "extraskeletal myxoid chondrosarcoma",
        "MONDO:0012825",
    ],
    "Cervical Adenocarcinoma": ["cervical adenocarcinoma", "EFO:0001416"],
    "Papillary Thyroid Cancer": ["Papillary thyroid cancer", "EFO:0000641"],
    "Choriocarcinoma": ["choriocarcinoma", "EFO:0002893"],
    "Splenic Marginal Zone Lymphoma": [
        "splenic marginal zone lymphoma",
        "MONDO:0019462",
    ],
    "Liposarcoma": ["liposarcoma", "EFO:0000569"],
    "Clear Cell Sarcoma": ["clear cell sarcoma", "EFO:0008498"],
    "High-Grade B-Cell Lymphoma, with MYC and BCL2 and/or BCL6 Rearrangements": [
        "high grade B-cell lymphoma",
        "MONDO:0044889",
    ],
    "Follicular Lymphoma": ["Follicular lymphoma", "EFO:0000096"],
    "Well-Differentiated Liposarcoma": [
        "well-differentiated liposarcoma",
        "EFO:0000736",
    ],
    "Dedifferentiated Liposarcoma": [
        "dedifferentiated liposarcoma",
        "EFO:0000569",
    ],
    "Breast Neoplasm, NOS": ["breast neoplasm", "MONDO:0021100"],
    "Matched Normal": ["healthy", None],
    "Hepatocellular Carcinoma plus Intrahepatic Cholangiocarcinoma": [
        "carcinoma of liver and intrahepatic biliary tract",
        "MONDO:0018531",
    ],
    "Immortalized Cholangiocyte, Highly Differentiated": ["healthy", None],
    "Gallbladder Cancer": ["Gallbladder cancer", "C0153452"],
    "Glassy Cell Carcinoma of the Cervix": [
        "cervical adenosquamous carcinoma, glassy cell variant",
        "MONDO:0004542",
    ],
    "Poorly Differentiated Non-Small Cell Lung Cancer": [
        "non-small cell lung carcinoma",
        "MONDO:0005233",
    ],
    "Ovarian Cancer, Other": ["ovarian carcinoma", "MONDO:0005140"],
    "Mucosal Melanoma of the Vulva/Vagina": ["vaginal melanoma", "MONDO:0006489"],
    "Sinonasal Squamous Cell Carcinoma": [
        "non-keratinizing sinonasal squamous cell carcinoma",
        "MONDO:0002831",
    ],
    "Extra Gonadal Germ Cell Tumor": [
        "extragonadal germ cell cancer",
        "MONDO:0003113",
    ],
    "Acute Leukemias of Ambiguous Lineage": [
        "acute leukemia of ambiguous lineage",
        "MONDO:0019460",
    ],
    "Malignant Peripheral Nerve Sheath Tumor": [
        "malignant peripheral nerve sheath tumor",
        "EFO:0000760",
    ],
    "Pleural Mesothelioma": ["pleural mesothelioma", "EFO:1000485"],
    "Granulosa Cell Tumor": ["granulosa cell tumor", "EFO:1000032"],
    "Small Cell Carcinoma of the Cervix": [
        "cervical small cell carcinoma",
        "MONDO:0006142",
    ],
    "Chordoma": ["chordoma", "MONDO:0008978"],
    "Immortalized Blood": ["healthy", None],
    "Head and Neck Carcinoma, Other": [
        "head and neck carcinoma",
        "MONDO:0002038",
    ],
    "Mucoepidermoid Carcinoma": ["lung mucoepidermoid carcinoma", "EFO:0006740"],
    "Primary Mediastinal (Thymic) Large B-Cell Lymphoma (PMBL)": [
        "primary mediastinal large B-cell lymphoma",
        "MONDO:0020323",
    ],
    "Acute Myelomonocytic Leukemia": [
        "acute myelomonocytic leukemia",
        "EFO:0000223",
    ],
    "B lymphoblast": ["healthy", None],
    "Spherocytosis": ["Spherocytosis", "HP:0004444"],
    "Gastrointestinal Stromal Tumor": [
        "gastrointestinal stromal tumor",
        "MONDO:0011719",
    ],
    "Immortalized Epithelial Cells, Corneal": ["healthy", None],
    "Diffuse Intrinsic Pontine Glioma": [
        "diffuse intrinsic pontine glioma",
        "EFO:1000026",
    ],
    "Immortalized Epithelial Cells, Retinal": ["healthy", None],
    "Acral Melanoma": ["acral lentiginous melanoma", "MONDO:0003865"],
    "Cholangiocarcinoma": ["cholangiocarcinoma", "EFO:0005221"],
    "High-Grade Neuroendocrine Carcinoma of the Colon and Rectum": [
        "high-grade neuroendocrine carcinoma of the corpus uteri",
        "MONDO:0016269",
    ],
    "Myxoid/Round-Cell Liposarcoma": [
        "myxoid/round cell liposarcoma",
        "MONDO:0020561",
    ],
    "Adenoid Cystic Carcinoma": ["adenoid cystic carcinoma", "MONDO:0004971"],
    "AML with Minimal Differentiation": [
        "acute myeloid leukemia with minimal differentiation",
        "MONDO:0005223",
    ],
    "Desmoid/Aggressive Fibromatosis": ["desmoid tumor", "MONDO:0007608"],
    "Pleomorphic Rhabdomyosarcoma": [
        "pleomorphic rhabdomyosarcoma",
        "MONDO:0017386",
    ],
    "Myxofibrosarcoma": ["myxofibrosarcoma", "MONDO:0019202"],
    "Dermatofibrosarcoma Protuberans": [
        "dermatofibrosarcoma protuberans",
        "MONDO:0011934",
    ],
    "Prostate Neuroendocrine Carcinoma": [
        "prostate neuroendocrine neoplasm",
        "MONDO:0002477",
    ],
    "Alveolar Soft Part Sarcoma": ["alveolar soft part sarcoma", "EFO:0007143"],
    "Immortalized Human Intervertebral Disc Cartilage Endplate-derived Stem Cells": [
        "healthy",
        None,
    ],
    "Immortalized Human Chondrocytes": ["healthy", None],
    "Immortalized Human Pancreatic Mesenchymal Stem Cells": ["healthy", None],
    "Immortalized Astrocytes": ["healthy", None],
    "Immortalized Endothelial Cells, Endoneurial": ["healthy", None],
    "Immortalized Cardiomyocytes": ["healthy", None],
    "immortalized Smooth Muscle Cells, Coronary artery": ["healthy", None],
    "Immortalized Smooth Muscle Cells, Pulmonary artery": ["healthy", None],
    "Immortalized Epithelial Cells, Renal": ["healthy", None],
    "Immortalized Endothelial Cells, Umbilical Vein": ["healthy", None],
    "Immortalized Submandibular Gland Cells": ["healthy", None],
    "Immortalized Neuronal Progenitor Cells": ["healthy", None],
    "Immortalized Skeletal Muscle Cells": ["healthy", None],
    "Immortalized Epithelial Cells, Lung": ["healthy", None],
    "Immortalized Liver Cells": ["healthy", None],
    "Immortalized MPLC Cells": ["healthy", None],
    "Immortalized Smooth Muscle Cells, Intestinal": ["healthy", None],
    "Immortalized Hair Follicle Inner Root Sheath Cells": ["healthy", None],
    "Immortalized Hair Germinal Matrix Cells": ["healthy", None],
    "Immortalized Pancreatic Stromal Cells": ["healthy", None],
    "Giant Cell Tumor of Bone": ["bone giant cell tumor", "MONDO:0005674"],
    "T-Cell Prolymphocytic Leukemia": [
        "T-cell prolymphocytic leukemia",
        "MONDO:0019468",
    ],
}
